// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBalance = "balance"

// Balance mapped from table <balance>
type Balance struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64     `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`
	Balance    float64   `gorm:"column:balance;default:0.00;comment:余额(元)" json:"balance"`
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Balance's table name
func (*Balance) TableName() string {
	return TableNameBalance
}
