// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImageType = "image_type"

// ImageType mapped from table <image_type>
type ImageType struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:图片类型 ID、自增" json:"id"`
	TypeName   string    `gorm:"column:type_name;comment:图片类型名称" json:"type_name"`
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:记录创建时间" json:"create_time"`
}

// TableName ImageType's table name
func (*ImageType) TableName() string {
	return TableNameImageType
}
