// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectUserRelation = "project_user_relation"

// ProjectUserRelation mapped from table <project_user_relation>
type ProjectUserRelation struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID     int64     `gorm:"column:project_id;not null;comment:项目id" json:"project_id"`
	PublishUserID int64     `gorm:"column:publish_user_id;comment:发布需求的用户id" json:"publish_user_id"`
	ReceiveUserID int64     `gorm:"column:receive_user_id;comment:接受需求的用户id" json:"receive_user_id"`
	CollectUserID int64     `gorm:"column:collect_user_id;comment:收藏用户id" json:"collect_user_id"`
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:记录创建时间" json:"create_time"`
	IsDeveloper   int32     `gorm:"column:is_developer;not null;comment:接单成功(1成功，0未成功，2为拒绝接单)，默认0" json:"is_developer"`
	IsCollect     int32     `gorm:"column:is_collect;comment:是否收藏（1收藏，0未收藏），默认0" json:"is_collect"`
}

// TableName ProjectUserRelation's table name
func (*ProjectUserRelation) TableName() string {
	return TableNameProjectUserRelation
}
