// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProjectPositionTypeRelation = "project_position_type_relation"

// ProjectPositionTypeRelation mapped from table <project_position_type_relation>
type ProjectPositionTypeRelation struct {
	ID             int64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:关联表自增ID" json:"id"`
	ProjectID      int64 `gorm:"column:project_id;comment:项目ID" json:"project_id"`
	PositionTypeID int64 `gorm:"column:position_type_id;comment:项目所需的工程师类型ID，对应position_type表中的id字段" json:"position_type_id"`
}

// TableName ProjectPositionTypeRelation's table name
func (*ProjectPositionTypeRelation) TableName() string {
	return TableNameProjectPositionTypeRelation
}
