// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectType = "project_type"

// ProjectType mapped from table <project_type>
type ProjectType struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TypeName    string    `gorm:"column:type_name;not null;comment:项目类型" json:"type_name"`
	TypeExplain string    `gorm:"column:type_explain;not null;comment:类型说明" json:"type_explain"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName ProjectType's table name
func (*ProjectType) TableName() string {
	return TableNameProjectType
}
