// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectScheduleRelation = "project_schedule_relation"

// ProjectScheduleRelation mapped from table <project_schedule_relation>
type ProjectScheduleRelation struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID  int64     `gorm:"column:project_id;not null;comment:项目id" json:"project_id"`
	ScheduleID int64     `gorm:"column:schedule_id;not null;comment:状态id" json:"schedule_id"`
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`
}

// TableName ProjectScheduleRelation's table name
func (*ProjectScheduleRelation) TableName() string {
	return TableNameProjectScheduleRelation
}
