// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	ID                  int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:项目 ID、自增" json:"id"`
	ProjectPublisherID  int64     `gorm:"column:project_publisher_id;not null;comment:项目发布者id" json:"project_publisher_id"`
	ProjectName         string    `gorm:"column:project_name;not null;comment:项目名字" json:"project_name"`
	ProjectLogo         string    `gorm:"column:project_logo;comment:项目logo" json:"project_logo"`
	ProjectBudget       float64   `gorm:"column:project_budget;default:0.00;comment:项目预算，保留两位小数，单位是元" json:"project_budget"`
	ProjectShortIntro   string    `gorm:"column:project_short_intro;comment:项目简介" json:"project_short_intro"`
	ProjectIntroduction string    `gorm:"column:project_introduction;not null;comment:项目介绍" json:"project_introduction"`
	ProjectDuration     string    `gorm:"column:project_duration;comment:项目周期，单位是天" json:"project_duration"`
	WorkExplain         string    `gorm:"column:work_explain;comment:工作内容说明" json:"work_explain"`
	StartTime           time.Time `gorm:"column:start_time;default:CURRENT_TIMESTAMP;comment:项目开始时间" json:"start_time"`
	EndTime             time.Time `gorm:"column:end_time;default:CURRENT_TIMESTAMP;comment:项目结束时间" json:"end_time"`
	CreateTime          time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`
	UpdateTime          time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:最后一次更新时间" json:"update_time"`
	ScheduleID          int64     `gorm:"column:schedule_id;comment:项目进度id" json:"schedule_id"`
	IsCompanyPublish    int32     `gorm:"column:is_company_publish;comment:企业发布为1，个人发布为2" json:"is_company_publish"`
	WorkType            int32     `gorm:"column:work_type;comment:工作类型（0为全职，1为兼职，2为全职兼职都可）" json:"work_type"`
	DeleteTag           int32     `gorm:"column:delete_tag;comment:删除标志（默认0，删除改为1）" json:"delete_tag"`
	Approved            int32     `gorm:"column:approved;comment:是否审核通过(通过为1，不通过为2)" json:"approved"`
	Approver            int64     `gorm:"column:approver;comment:审核人id" json:"approver"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
