// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectNotPlatform = "project_not_platform"

// ProjectNotPlatform mapped from table <project_not_platform>
type ProjectNotPlatform struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`
	ProjectName  string    `gorm:"column:project_name;comment:非平台项目名称" json:"project_name"`
	ProjectIntro string    `gorm:"column:project_intro;comment:非平台项目介绍" json:"project_intro"`
	StartTime    time.Time `gorm:"column:start_time;comment:非平台项目开始时间" json:"start_time"`
	EndTime      time.Time `gorm:"column:end_time;comment:非平台项目结束时间" json:"end_time"`
	CreateTime   time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName ProjectNotPlatform's table name
func (*ProjectNotPlatform) TableName() string {
	return TableNameProjectNotPlatform
}
