// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserWork = "user_works"

// UserWork mapped from table <user_works>
type UserWork struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`
	CompanyName string    `gorm:"column:company_name;comment:公司名称" json:"company_name"`
	StationName string    `gorm:"column:station_name;comment:岗位名称" json:"station_name"`
	WorkContent string    `gorm:"column:work_content;comment:工作内容" json:"work_content"`
	StartTime   time.Time `gorm:"column:start_time;comment:工作开始时间" json:"start_time"`
	EndTime     time.Time `gorm:"column:end_time;comment:工作结束时间" json:"end_time"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName UserWork's table name
func (*UserWork) TableName() string {
	return TableNameUserWork
}
