// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserPositionTypeRelation = "user_position_type_relation"

// UserPositionTypeRelation mapped from table <user_position_type_relation>
type UserPositionTypeRelation struct {
	ID             int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         int64 `gorm:"column:user_id" json:"user_id"`
	PositionTypeID int64 `gorm:"column:position_type_id" json:"position_type_id"`
}

// TableName UserPositionTypeRelation's table name
func (*UserPositionTypeRelation) TableName() string {
	return TableNameUserPositionTypeRelation
}
