// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserEducation = "user_educations"

// UserEducation mapped from table <user_educations>
type UserEducation struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`
	CollegeName    string    `gorm:"column:college_name;comment:学校名称" json:"college_name"`
	MajorName      string    `gorm:"column:major_name;comment:专业名称" json:"major_name"`
	DegreeName     string    `gorm:"column:degree_name;comment:学位名称" json:"degree_name"`
	EducationIntro string    `gorm:"column:education_intro;comment:教育经历简介" json:"education_intro"`
	StartTime      time.Time `gorm:"column:start_time;comment:开始时间" json:"start_time"`
	EndTime        time.Time `gorm:"column:end_time;comment:结束时间" json:"end_time"`
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:记录创建时间" json:"create_time"`
	EntranceTime   string    `gorm:"column:entrance_time;comment:入学时间" json:"entrance_time"`
}

// TableName UserEducation's table name
func (*UserEducation) TableName() string {
	return TableNameUserEducation
}
