// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserImage = "user_images"

// UserImage mapped from table <user_images>
type UserImage struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`
	ImageTypeID int64     `gorm:"column:image_type_id;comment:照片类型id" json:"image_type_id"`
	Image       string    `gorm:"column:image;comment:照片路径" json:"image"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName UserImage's table name
func (*UserImage) TableName() string {
	return TableNameUserImage
}
