// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserSkillTypeRelation = "user_skill_type_relation"

// UserSkillTypeRelation mapped from table <user_skill_type_relation>
type UserSkillTypeRelation struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增 ID" json:"id"`
	UserID     int64     `gorm:"column:user_id;comment:用户 ID" json:"user_id"`
	SkillID    int64     `gorm:"column:skill_id;comment:技能 ID" json:"skill_id"`
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:记录创建时间" json:"create_time"`
}

// TableName UserSkillTypeRelation's table name
func (*UserSkillTypeRelation) TableName() string {
	return TableNameUserSkillTypeRelation
}
