// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWorkState = "work_state"

// WorkState mapped from table <work_state>
type WorkState struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StateType    string    `gorm:"column:state_type;not null;comment:工作状态类型" json:"state_type"`
	StateExplain string    `gorm:"column:state_explain;comment:工作状态说明" json:"state_explain"`
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:记录创建时间" json:"create_time"`
}

// TableName WorkState's table name
func (*WorkState) TableName() string {
	return TableNameWorkState
}
